[package]
name = "openslide-rs"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openslide-sys = { path = "openslide-sys" }
image = "0.23"
byteorder = "1.3"

[workspace]
members = [
    "openslide-py",
    "openslide-sys"
]