[package]
name = "openslide-sys"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.60.1"
cc = "1.0"
pkg-config = "0.3"