name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Apt update
      run: apt update
    - name: Install dependencies
      run: ./install_dependencies.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
